
version: '3.8'

networks:
  petconsult-network:
    driver:
      bridge

services:
  postgresql:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: MyPass01
      POSTGRES_USER: petconsult
      POSTGRES_DB: petconsultdb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - petconsult-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fulano@email.com"
      PGADMIN_DEFAULT_PASSWORD: "MyPass01"
    ports:
      - "16543:80"
    depends_on:
      - postgresql
    networks:
      - petconsult-network


  petconsult: 
    image: jersonb/petconsult:latest
    depends_on: 
      - postgresql
    container_name: petconsult
    restart: always
    ports:
      - 5000:80
    networks:
      - petconsult-network

  devops-app_front:
    image: devops-app:latest
    build:
      context: ../../cadastroPet-front
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - petconsult-network

volumes:
  postgres:
